Added assignment of week 2
pesto-students/p5-subhadip-Dibya12345 pull request #3
Opened 2022-08-27 08:20 UTC by Dibya12345

This is the assignment of Week 2

2022-08-29 09:41 UTC, subhadip-pesto commented
Please fix all places where you have maintained the alignment with position:relative and top/right/left/botto, properties.

2022-08-29 09:46 UTC, Dibya12345 commented
Sure Do I have to remove all the position property

2022-08-30 15:03 UTC, subhadip-pesto requested changes

2022-08-30 15:03 UTC, subhadip-pesto commented on Week-2/Question(2.2)/style.css
> +    position: relative;
Please fix all places where you have maintained the alignment with position:relative and top/right/left/bottom, properties.

2022-09-01 03:18 UTC, subhadip-pesto requested changes

2022-09-01 03:18 UTC, subhadip-pesto commented on Week-2/Question(2.2)/style.css
> +    position: relative;
here also

2022-09-01 04:56 UTC, Dibya12345 commented on Week-2/Question(2.2)/style.css
> +    position: relative;
I resolved it

2022-09-01 04:57 UTC, Dibya12345 commented on Week-2/Question(2.2)/style.css
> +    position: relative;
Resolved it can u check now

2022-09-03 04:18 UTC, subhadip-pesto approved these changes

2022-09-07 15:14 UTC, merged